"""Collect community-response KPIs from GitHub repositories.

Same algorithm as the team's KPI notebook, with fast data access:
- 100 items per page instead of 30
- no lazy per-item fetches (merged_at instead of pr.merged; raw payload
  key instead of issue.pull_request)
- the closed-PR scan sorts by `updated` and exits early (a PR cannot
  close after its last update)
- per-item detail fetches (reviews, comments, timelines) run in a
  thread pool

Verified byte-identical to the notebook's output on redis/node-redis.
"""

import os
import subprocess
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone

import pandas as pd
import yaml
from github import Github

WORKERS = 10


def get_token():
    token = os.environ.get("GITHUB_TOKEN") or subprocess.run(
        ["gh", "auth", "token"], capture_output=True, text=True
    ).stdout.strip()
    if not token:
        raise RuntimeError(
            "No GitHub token. Set the GITHUB_TOKEN environment variable "
            "or log in with `gh auth login`."
        )
    return token


def current_quarter(now):
    """Redis fiscal quarters. The fiscal year starts Feb 1:
    Q1 Feb-Apr, Q2 May-Jul, Q3 Aug-Oct, Q4 Nov-Jan."""
    if now.month == 1:
        start = datetime(now.year - 1, 11, 1, tzinfo=timezone.utc)
    else:
        month = {2: 2, 3: 2, 4: 2, 5: 5, 6: 5, 7: 5, 8: 8, 9: 8, 10: 8, 11: 11, 12: 11}[now.month]
        start = datetime(now.year, month, 1, tzinfo=timezone.utc)

    if start.month == 11:
        end = datetime(start.year + 1, 2, 1, tzinfo=timezone.utc)
    else:
        end = datetime(start.year, start.month + 3, 1, tzinfo=timezone.utc)

    number = {2: 1, 5: 2, 8: 3, 11: 4}[start.month]
    fiscal_year = start.year + 1
    return start, end, f"Q{number}FY{fiscal_year % 100}"


def load_config(path):
    with open(path) as f:
        cfg = yaml.safe_load(f)

    quarter = cfg.get("quarter") or {}
    if quarter.get("start") and quarter.get("end"):
        start = datetime.fromisoformat(str(quarter["start"])).replace(tzinfo=timezone.utc)
        end = datetime.fromisoformat(str(quarter["end"])).replace(tzinfo=timezone.utc)
        label = quarter.get("label") or f"{quarter['start']} to {quarter['end']}"
    else:
        start, end, label = current_quarter(datetime.now(timezone.utc))

    cfg["start_date"], cfg["end_date"], cfg["quarter_label"] = start, end, label
    return cfg


def hours_since(then, now=None):
    now = now or datetime.now(timezone.utc)
    return (now - then).total_seconds() / 3600


def hours_between(a, b):
    return (b - a).total_seconds() / 3600 if a and b else None


def parse_github_datetime(value):
    if not value or isinstance(value, datetime):
        return value
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


class RepoCollector:
    def __init__(self, gh, repo_name, cfg, pool):
        self.repo = gh.get_repo(repo_name)
        self.cfg = cfg
        self.pool = pool
        self.start = cfg["start_date"]
        self.end = cfg["end_date"]

    # --- role checks ---------------------------------------------------------

    def is_maintainer(self, user):
        return user is not None and user.login in self.cfg["maintainers"]

    def is_ext_maintainer(self, user):
        return user is not None and user.login in self.cfg["external_maintainers"]

    def is_docs_team(self, user):
        return user.login in self.cfg["docs_team"]

    def is_team_author(self, user):
        return self.is_maintainer(user) or self.is_ext_maintainer(user)

    @staticmethod
    def is_autogenerated(pr):
        return pr.user.login == "dependabot[bot]"

    @staticmethod
    def is_pull(issue):
        # issue.pull_request would lazily re-fetch every plain issue: the
        # list payload omits the field for non-PRs. The raw payload answers.
        return "pull_request" in issue._rawData

    # --- pull requests -------------------------------------------------------

    def _pr_details(self, pr):
        """Reviews + comments scan for one PR (runs on a worker thread)."""
        counters = Counter()
        interactions = Counter()
        first_response = None
        merged = pr.merged_at is not None

        for review in pr.get_reviews():
            if self.is_maintainer(review.user):
                interactions[review.user.login] += 1
                if first_response is None or review.submitted_at < first_response:
                    first_response = review.submitted_at
                counters["reviewed"] += 1
                if review.state == "CHANGES_REQUESTED":
                    counters["requested_changes"] += 1
                elif review.state == "APPROVED":
                    counters["approved"] += 1

        for comment in pr.get_issue_comments():
            if self.is_maintainer(comment.user):
                interactions[comment.user.login] += 1
                if first_response is None or comment.created_at < first_response:
                    first_response = comment.created_at

        if first_response is None and merged:
            first_response = pr.merged_at

        # Skip PRs opened by mistake: closed without merge and never touched
        if first_response is None and pr.state == "closed" and not merged:
            return None, counters

        ttfr = hours_between(pr.created_at, first_response)
        closed_at = pr.merged_at if merged else pr.closed_at
        row = {
            "PR Number": pr.number,
            "Title": pr.title,
            "User": pr.user.login,
            "Resolved": merged,
            "Closed": pr.state == "closed",
            "Waiting for triage": first_response is None,
            "Unanswered for": ttfr if first_response else hours_since(pr.created_at),
            "Interactions": sum(interactions.values()),
            "Time to first response": ttfr,
            "Created At": pr.created_at,
            "Time to close": hours_between(pr.created_at, closed_at),
            "Link": pr.html_url,
        }
        return row, counters

    def _collect_prs(self, candidates):
        counters = Counter()
        rows = []
        for row, part in self.pool.map(self._pr_details, candidates):
            counters.update(part)
            if row is not None:
                rows.append(row)
        return pd.DataFrame(rows), counters

    def opened_prs(self):
        """Community PRs created inside the window."""
        candidates = []
        docs_open = []
        docs_merged = 0

        for pr in self.repo.get_pulls(state="all", sort="created", direction="desc"):
            if self.is_autogenerated(pr) or self.is_team_author(pr.user):
                continue
            if pr.created_at < self.start:
                break
            if pr.created_at > self.end:
                continue
            if self.is_docs_team(pr.user):
                if pr.draft:
                    continue
                if pr.merged_at is not None:
                    docs_merged += 1
                else:
                    docs_open.append({"PR Number": pr.number, "Title": pr.title,
                                      "User": pr.user.login, "Link": pr.html_url})
                continue
            candidates.append(pr)

        df, counters = self._collect_prs(candidates)
        return {"prs": df, "counters": counters,
                "docs_open": pd.DataFrame(docs_open), "docs_merged": docs_merged}

    def closed_prs(self):
        """Community PRs closed or merged inside the window."""
        candidates = []
        for pr in self.repo.get_pulls(state="all", sort="updated", direction="desc"):
            if pr.updated_at < self.start:
                break  # closed_at <= updated_at: nothing further can qualify
            if self.is_autogenerated(pr) or self.is_team_author(pr.user):
                continue
            if pr.state == "open":
                continue
            if pr.closed_at < self.start or pr.closed_at > self.end:
                continue
            candidates.append(pr)

        df, counters = self._collect_prs(candidates)
        if len(df):
            df = df.sort_values("PR Number", ascending=False).reset_index(drop=True)
        return {"prs": df, "counters": counters}

    # --- issues --------------------------------------------------------------

    def _issue_details(self, issue):
        """Comments + timeline scan for one issue (runs on a worker thread)."""
        interactions = Counter()
        first_response = None

        for comment in issue.get_comments():
            if self.is_maintainer(comment.user):
                interactions[comment.user.login] += 1
                if first_response is None or comment.created_at < first_response:
                    first_response = comment.created_at

        # Cross-referenced PRs count as responses: a maintainer reacting to a
        # linked fix PR (or opening one) is a response to the issue.
        try:
            for event in issue.get_timeline():
                if getattr(event, "event", None) != "cross-referenced":
                    continue
                source = getattr(event, "source", None)
                source_issue = getattr(source, "issue", None) if source else None
                if source_issue is None or not source_issue.pull_request:
                    continue
                if source_issue.repository.full_name != self.repo.full_name:
                    continue
                try:
                    pr = self.repo.get_pull(source_issue.number)
                except Exception:
                    continue

                if pr.user.login == issue.user.login:
                    try:
                        for review in pr.get_reviews():
                            if self.is_team_author(review.user):
                                if first_response is None or review.submitted_at < first_response:
                                    first_response = review.submitted_at
                    except Exception:
                        pass
                    try:
                        for comment in pr.get_issue_comments():
                            if comment.user and self.is_team_author(comment.user):
                                if first_response is None or comment.created_at < first_response:
                                    first_response = comment.created_at
                    except Exception:
                        pass
                elif self.is_team_author(pr.user):
                    if first_response is None or pr.created_at < first_response:
                        first_response = pr.created_at
        except Exception:
            pass

        if first_response is None:
            if issue.closed_by and self.is_team_author(issue.closed_by):
                first_response = issue.closed_at
            if issue.closed_by and issue.closed_by.login == issue.user.login:
                return None  # closed by its own author: skip

        ttfr = hours_between(issue.created_at, first_response)
        return {
            "Issue Number": issue.number,
            "Title": issue.title,
            "User": issue.user.login,
            "Resolved": issue.state == "closed",
            "Waiting for triage": first_response is None,
            "Unanswered for": ttfr if first_response else hours_since(issue.created_at),
            "Interactions": sum(interactions.values()),
            "Time to first response": ttfr,
            "Link": issue.html_url,
        }

    def opened_issues(self):
        candidates = []
        for issue in self.repo.get_issues(state="all", since=self.start):
            if issue.created_at > self.end or self.is_team_author(issue.user) or self.is_pull(issue):
                continue
            if issue.created_at < self.start:
                break
            candidates.append(issue)

        rows = [r for r in self.pool.map(self._issue_details, candidates) if r is not None]
        return pd.DataFrame(rows)

    def backlog_issues(self):
        """Open issues from before the window that never got a comment."""
        rows = []
        for issue in self.repo.get_issues(state="open", sort="created", direction="asc"):
            if issue.created_at > self.start:
                break  # sorted ascending by creation: no later issue qualifies
            if self.is_team_author(issue.user) or self.is_pull(issue):
                continue
            if issue.comments > 0:
                continue
            rows.append({
                "Issue Number": issue.number,
                "Title": issue.title,
                "User": issue.user.login,
                "Unanswered for": hours_since(issue.created_at),
                "Link": issue.html_url,
            })
        return pd.DataFrame(rows)

    # --- discussions ---------------------------------------------------------

    def discussions(self):
        schema = """
            id
            isAnswered
            number
            title
            author { login }
            createdAt
            answerChosenAt
            closed
            closedAt
            url
        """
        rows = []
        for discussion in self.repo.get_discussions(schema):
            if not (self.start < discussion.created_at < self.end):
                continue
            if self.is_team_author(discussion.author):
                continue

            interactions = Counter()
            first_response = None
            for comment in discussion.get_comments("author { login } createdAt url"):
                if self.is_maintainer(comment.author):
                    interactions[comment.author.login] += 1
                    if first_response is None or comment.created_at < first_response:
                        first_response = comment.created_at

            raw = discussion._rawData
            closed_at = parse_github_datetime(raw.get("answerChosenAt")) or parse_github_datetime(raw.get("closedAt"))
            if closed_at and (first_response is None or closed_at < first_response):
                first_response = closed_at

            ttfr = hours_between(discussion.created_at, first_response)
            rows.append({
                "Discussion Number": discussion.number,
                "Title": discussion.title,
                "User": discussion.author.login,
                "Resolved": raw.get("isAnswered", False) or raw.get("closed", False),
                "Waiting for triage": first_response is None,
                "Unanswered for": ttfr if first_response else hours_since(discussion.created_at),
                "Interactions": sum(interactions.values()),
                "Time to first response": ttfr,
                "Link": raw["url"],
            })
        return pd.DataFrame(rows)


def detractors(df, threshold_hours):
    """Split a stats frame into (still unanswered, slow first responses)."""
    if not len(df):
        return df, df
    unanswered = df[df["Waiting for triage"]].sort_values("Unanswered for", ascending=False)
    slow = df[df["Time to first response"] > threshold_hours].sort_values(
        "Time to first response", ascending=False
    )
    return unanswered, slow


def quantile(df, column, q=0.85):
    if not len(df) or df[column].dropna().empty:
        return None
    return round(float(df[column].quantile(q)), 2)


def collect_repo(gh, repo_name, cfg, pool):
    c = RepoCollector(gh, repo_name, cfg, pool)

    issues = c.opened_issues()
    backlog = c.backlog_issues()
    opened = c.opened_prs()
    closed = c.closed_prs()
    disc = c.discussions()

    threshold = cfg.get("slow_threshold_hours", 48)
    issue_unanswered, issue_slow = detractors(issues, threshold)
    pr_unanswered, pr_slow = detractors(opened["prs"], threshold)

    summary = {
        "Repository": repo_name,
        "Opened Issues": len(issues),
        "Closed Issues": int(issues["Resolved"].sum()) if len(issues) else 0,
        "Issues Response Time (h, p85)": quantile(issues, "Time to first response"),
        "Issues Waiting Time (h, p85)": quantile(issues, "Unanswered for"),
        "Backlog of Untriaged Issues": len(backlog),
        "Opened PRs": len(opened["prs"]),
        "Merged PRs": int(opened["prs"]["Resolved"].sum()) if len(opened["prs"]) else 0,
        "Closed PRs": len(closed["prs"]),
        "PRs Response Time (h, p85)": quantile(opened["prs"], "Time to first response"),
        "PRs Waiting Time (h, p85)": quantile(opened["prs"], "Unanswered for"),
        "Opened Discussions": len(disc),
        "Closed Discussions": int(disc["Resolved"].sum()) if len(disc) else 0,
        "Discussions Response Time (h, p85)": quantile(disc, "Time to first response"),
        "Interactions": int(
            (issues["Interactions"].sum() if len(issues) else 0)
            + (opened["prs"]["Interactions"].sum() if len(opened["prs"]) else 0)
            + (disc["Interactions"].sum() if len(disc) else 0)
        ),
    }

    return {
        "name": repo_name,
        "summary": summary,
        "issues": issues,
        "backlog": backlog,
        "opened": opened,
        "closed": closed,
        "discussions": disc,
        "detractors": {
            "issues_unanswered": issue_unanswered,
            "issues_slow": issue_slow,
            "prs_unanswered": pr_unanswered,
            "prs_slow": pr_slow,
        },
    }


def collect(cfg):
    gh = Github(get_token(), per_page=100)
    with ThreadPoolExecutor(max_workers=WORKERS) as pool:
        return [collect_repo(gh, name, cfg, pool) for name in cfg["repos"]]
